### PR TITLE
Changing license to Apache 2.0

### PR DESCRIPTION
**Pull request by mkdbns**

### CODE REVIEW

**Comment by jfrerich** [comment]
Hey @mkdbns! Hope you've been well.  Is there an associated ticket with this change or someone that is aware of this change that I could add as reviewer?

**Comment by mkdbns** [comment]
@jfrerich , sorry, just seeing this. Stu Doherty asked me to make these changes.

**Comment by sadohert** [comment]
Thanks all.  The request was based on internal discussions and the more common licensing practice for our plugins.  Approving.

**Review by sadohert — APPROVED** [review]
LGTM!

**Pull request merged**
